export const mockUsers = [
  {
    id: "USR001",
    name: "John Smith",
    email: "john.smith@example.com",
    status: "pending",
    verified: false,
    createdAt: "2024-12-15",
    kyc: {
      documents: ["Passport ID", "Proof of Address"],
    },
  },
  {
    id: "USR002",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    status: "active",
    verified: true,
    createdAt: "2024-11-20",
    kyc: {
      documents: ["Driver License", "Bank Statement"],
      verificationDate: "2024-12-01",
    },
  },
  {
    id: "USR003",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    status: "active",
    verified: true,
    createdAt: "2024-10-10",
    kyc: {
      documents: ["National ID", "Tax Document"],
      verificationDate: "2024-11-15",
    },
  },
  {
    id: "USR004",
    name: "Emma Davis",
    email: "emma.davis@example.com",
    status: "pending",
    verified: false,
    createdAt: "2025-01-01",
    kyc: {
      documents: ["Passport"],
    },
  },
  {
    id: "USR005",
    name: "James Wilson",
    email: "james.wilson@example.com",
    status: "inactive",
    verified: false,
    createdAt: "2024-09-05",
    kyc: {
      documents: [],
    },
  },
];

export const mockTransactions = [
  {
    id: "TXN000001",
    senderId: "john.smith@example.com",
    receiverId: "sarah.johnson@example.com",
    amount: 5000,
    status: "completed",
    createdAt: "2024-12-20",
    updatedAt: "2024-12-20",
  },
  {
    id: "TXN000002",
    senderId: "michael.brown@example.com",
    receiverId: "emma.davis@example.com",
    amount: 15000,
    status: "pending",
    createdAt: "2024-12-21",
    updatedAt: "2024-12-21",
  },
  {
    id: "TXN000003",
    senderId: "sarah.johnson@example.com",
    receiverId: "michael.brown@example.com",
    amount: 8500,
    status: "completed",
    createdAt: "2024-12-19",
    updatedAt: "2024-12-19",
  },
  {
    id: "TXN000004",
    senderId: "emma.davis@example.com",
    receiverId: "john.smith@example.com",
    amount: 3200,
    status: "failed",
    createdAt: "2024-12-18",
    updatedAt: "2024-12-18",
  },
  {
    id: "TXN000005",
    senderId: "james.wilson@example.com",
    receiverId: "sarah.johnson@example.com",
    amount: 12000,
    status: "completed",
    createdAt: "2024-12-17",
    updatedAt: "2024-12-17",
  },
];

export const mockEscrows = [
  {
    id: "ESC0001",
    buyerId: "john.smith@example.com",
    sellerId: "sarah.johnson@example.com",
    amount: 25000,
    status: "held",
    description: "Electronics Purchase - Laptop",
    createdAt: "2024-12-20",
  },
  {
    id: "ESC0002",
    buyerId: "michael.brown@example.com",
    sellerId: "emma.davis@example.com",
    amount: 50000,
    status: "pending",
    description: "Real Estate Transaction - Property Deal",
    createdAt: "2024-12-21",
  },
  {
    id: "ESC0003",
    buyerId: "sarah.johnson@example.com",
    sellerId: "michael.brown@example.com",
    amount: 15000,
    status: "released",
    description: "Freelance Project Completion - Web Development",
    createdAt: "2024-12-19",
  },
  {
    id: "ESC0004",
    buyerId: "emma.davis@example.com",
    sellerId: "john.smith@example.com",
    amount: 8000,
    status: "cancelled",
    description: "Service Agreement - Cancelled",
    createdAt: "2024-12-15",
  },
  {
    id: "ESC0005",
    buyerId: "james.wilson@example.com",
    sellerId: "sarah.johnson@example.com",
    amount: 35000,
    status: "held",
    description: "Vehicle Purchase - Car Sale",
    createdAt: "2024-12-18",
  },
];
